### DISCUSSION TITLE
How to setup

### DISCUSSION THREAD

**Discussion by YahyaaAyman** [t348575/twitch-points-miner#4] [Q&A] [answered]
Explain to me how to use it , like i'm 6 yo

**Comment by t348575** [comment, marked as answer]
1. Install [docker](https://www.docker.com/)
2. Run `docker run -i -t -v ./data:/data t348575/twitch-points-miner --token /data/tokens.json` in a terminal window
3. Go to `https://www.twitch.tv/activate` in your browser and enter the code shown in the terminal window
5. Once you are logged in, enter "y" in the terminal window, then CTRL+C to exit the app.
6. Setup a config.yaml file in the same folder: [refer](https://github.com/t348575/twitch-points-miner/blob/master/example.config.yaml)
7. Setup a docker-compose.yaml file as outlined in the README, making sure to change the line `./tokens.json:/tokens.json` to `./data/tokens.json:/tokens.json`
8. Run `docker compose up -d` in the terminal
9. The web UI should be accessible at `http://localhost:3000`

**Reply by YahyaaAyman** [reply]
![Screenshot 2024-04-26 131049](https://github.com/t348575/twitch-points-miner/assets/165519906/15395ee5-2d93-42a1-840a-da3372d0c2af)

**Reply by t348575** [reply]
Yep this is fine, because a config file was not specified in the initial command. You should see a "tokens.json" in the data folder now

**Reply by YahyaaAyman** [reply]
![image](https://github.com/t348575/twitch-points-miner/assets/165519906/34d07bcc-ab07-4d0c-a394-5f9bf391e22f)

after everything i get this

**Reply by t348575** [reply]
This is because docker creates folders by default for volumes, so you need to create blank files first.
1. Run `docker compose down`
2. Delete folders called `analytics.db` and `twitch-points-miner.log`
3. Create blank files for the above with the same name, use `touch` if on linux or mac, eg. `touch analytics.db` or if on windows: `type nul >> "analytics.db"`
4. Run `docker compose up -d`

**Reply by YahyaaAyman** [reply]
![image](https://github.com/t348575/twitch-points-miner/assets/165519906/00876209-1420-4d32-ae5e-f3fcdea99a46)

It never ends 😂 , sorry

**Reply by t348575** [reply]
As the error says, you're missing the "default" field in that strategy (most likely you did not tab correctly). Attach your config file here. Btw I suggest checking this repo every once in a while for updates (since its still early and bugs exist), and running `docker compose pull` followed by `docker compose restart` to update the app.

**Reply by YahyaaAyman** [reply]
if i got it right i need to add "default" to the `presets.small.prediction.strategy` but i can't find where is it to add the "default" to it

**Reply by t348575** [reply]
Ok looks like the example has a tabbing typo. Use this:
```yaml
presets:
  # a preset configuration that can be reused
  # this particular one only defines a base range
  small:
    follow_raid: false
    prediction:
      strategy: !detailed
        default:
          max_percentage: 0.0
          min_percentage: 0.0
          points:
            max_value: 0
            percent: 0.0
      filters: []
```
